name: bomcop
description: "A tool to verify that all your files contain a UTF-8 BOM"
branding:
  icon: activity
  color: orange
inputs:
  exclude:
    description: "List of file regex patterns to be excluded"
    required: false
    default: "?"
runs:
  using: docker
  image: Dockerfile
  args:
    - "--exclude"
    - ${{ inputs.exclude }}
