name: Run bomcop
on:
  push:
  pull_request:
jobs:
  build:
    name: Run bomcop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run bomcop
        uses: samuelmasse/bomcop@master
        with:
          exclude: "action.yml"
